{
 "title": "NBI Analytics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "GNB CPU Usage ( Percentage )",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "gnb_cpu", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "GNB Memory Usage",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gnb_ram", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Number of PDU sessions in the network",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "num_pdu", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Number of UEs in the network",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "num_ue", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "End-to-End Delay",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ue_e2e_delay", "legendFormat": "{{name}}" }
   ]
  }
 ]
}